### ISSUE TITLE
Compile ES5 version for npm

### ISSUE THREAD

**Issue by OmgImAlexis** [rosendin/vue-bulma-typeahead#1]
It's recommended to use a compiled version of vue models when publishing to npm as this prevents users needing babel setup to transpile third party deps.

You're also missing babel presets to allow importing and exporting. I'd suggest adding `babel-preset-es2015` to fix this.

For example importing your component currently just throws errors.
```
/Users/xo/code/Twistly/frontend/node_modules/vue-bulma-typeahead/index.js:1
import Typeahead from './src/Typeahead.vue'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

[Here's a good guide on building for npm](https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/).

You should also be using the built file from `dist` as your main script instead of your source so people using ES5 don't need to recompile it at runtime.

You may also want to checkout [this](https://forum-archive.vuejs.org/topic/3682/create-npm-packages-from-a-vue-file/5) to allow people to use it properly with browserify, etc.

**Comment by rosendin** [comment]
Thanks for the detailed write-up, @OmgImAlexis. This issue should be fixed in 0.0.6 and the documentation has been updated to fix the import line.
